# Generated by Django 4.2.2 on 2023-08-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('title', models.CharField(max_length=80, verbose_name='brand')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.country')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('model', models.CharField(max_length=80, verbose_name='model name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('color_name', models.CharField(max_length=80, verbose_name='color name')),
                ('color_code', models.CharField(help_text='color code for eg: #010232', max_length=9, verbose_name='color code')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='size')),
                ('is_available', models.BooleanField(verbose_name='is available')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.brand')),
                ('producer_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.country', verbose_name='producer country')),
            ],
            options={
                'verbose_name': 'mobile',
                'verbose_name_plural': 'mobiles',
                'indexes': [models.Index(fields=['model', 'is_available'], name='inventory_m_model_9b63db_idx')],
                'unique_together': {('brand', 'model')},
            },
        ),
    ]
