# Generated by Django 4.2.2 on 2023-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_mobile_color_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'ordering': ('created_at',), 'verbose_name': 'mobile', 'verbose_name_plural': 'mobiles'},
        ),
        migrations.AlterField(
            model_name='mobile',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='size'),
        ),
    ]
